version: '2.4'

services:

  ubuntu18-systemd:
    container_name: ubuntu18-systemd
    hostname: ubuntu
    image: adiprint/ubuntu18-systemd:latest
    privileged: true
    stdin_open: false
    network_mode: bridge
    tty: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: "no"
